### ISSUE TITLE
Any possibility of 1.18 support?

### ISSUE THREAD

**Issue by mrphi06** [CaelTheColher/KeybindsGalore#2]
Is there any possibility of 1.18 support? Or has this project been abandoned? I use this mod a lot, but it currently does not have any 1.18 version. Honestly, great mod, very simple and effective. Have a nice day!

**Comment by CaelTheColher** [comment]
Working on it

**Comment by CaelTheColher** [comment]
should be released on curseforge soon, meanwhile it can be downloaded on modrinth and here on github
